// AUTO-GENERATED by scripts/gen-blur.mjs — do not edit by hand.
// Base64 blur placeholders keyed by public path, used by next/image.
export const blurData: Record<string, string> = {
  "/foto/aldo.jpg": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBACdASoUAA0APu1iqU2ppaOiMAgBMB2JagCdH8GJ/gLgAcpaFn/lDADeUxDPY1fIh7/rQMlR14AXmpRew85AcTV5WKsrnVggW6OrY/ls5zPUDKiEDovqUWfXqO0cGGfqALMl8vIoOreEHINhRjcUe7QYwAAA",
  "/foto/alzaia.jpg": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAwCdASoUAA0APu1kqU2ppaQiMAgBMB2JYwCsAB6NaPZdH2JiloAA/gdobHKGuYjmo9jiISi8B2qqY450OJMWkx/8EsIss6pKh6CK+9Hx7J5erDSTbq56slrf3O5Njlkk3oAAAAA=",
  "/foto/castello.jpg": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAADwAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JZwDCgCKPSz1Un7G8NYYAAP7n+8c5MzHhM0Pzf1bfAUiPkQ3FiZLwJVysg8+6X59wuaQ9WLLfG4T/04gVj8boGzVq3rMzL0+vp+gSXJ+Qn1w5Eg7zqM6+dz/uayifEgFFgdfkOQAAAA==",
  "/foto/cellore.jpg": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADQAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JYwC7AB2WpTAjUKxT6IAA/uqQB4nwXB3GvQa1mMUESea5iSOtmWcrR8MzzJYuytPGbRsu009eLjRsGzoW7QrCX0DVqz2wT2RIznp+dzp7re5vIBIOlngtXyoAAA==",
  "/foto/giambellino.jpg": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAwCdASoUAA0APu1kqU2ppaOiMAgBMB2JYwC/OBig++mK06ZYAAD+xVTdimi6UnC46UbtTWI4GDA2oR9nAMZqZPiY6Q5R7mP/fYwLwxHrLHBvKWv4GL9b3CLVsPAA",
  "/foto/guastalla.jpg": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACQAwCdASoUAA8APu1iqk2ppaQiMAgBMB2JYwCsAC0H4MoQpaQAAP7vr6QNWexg1FI/CORp0EST+PXWJRQrFgAA",
  "/foto/hero-legno.jpg": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACQBACdASoUAA0APu1iqk4ppaQiMAgBMB2JYgCdMoRwN0AAKjXy6HJTASfyNAAA/ukd4eX1kaSuTC/2sM6Pf/6uQ+p6ilViBJ7Sr3Tt8S7v3osUwoBwHx3GeqVbLnHkopB9LZ68f5O9+AAA",
  "/foto/troppe-colonne.jpg": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQBACdASoUAA0APu1iqU2ppaOiMAgBMB2JYwCdISADAt7JXLvTBTshAAD+7n8Can+fxsTlszRU/XjFc4H2DgSYHaWvz/fG1FZh27d379JFh2vwM7F+SAhp4VR9borO4y9ucSgAAAA=",
  "/foto/troppo-tondo.jpg": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAwCdASoUAA0APu1iqU2ppaQiMAgBMB2JZQCdAB0+qlEyyl/ciE4AAP7qRVXVL9TWQjUCkVjGbM9q/lhMUrO4EFg6IT3sgFwoZbbRObjAsZ2plzrnWMAA"
};

export function blurFor(src: string): string | undefined {
  return blurData[src];
}
