// Generates tiny base64 blur placeholders for every photo in /public/foto.
// Run manually with `npm run blur` whenever the photography changes; the
// output (lib/blur.ts) is committed so production builds need no image
// processing at build time.
import { readdir, writeFile } from "node:fs/promises";
import { join, parse } from "node:path";
import sharp from "sharp";

const FOTO_DIR = join(process.cwd(), "public", "foto");
const OUT_FILE = join(process.cwd(), "lib", "blur.ts");

const files = (await readdir(FOTO_DIR))
  .filter((f) => /\.(jpe?g|png|webp|avif)$/i.test(f))
  .sort();

const entries = {};
for (const file of files) {
  const buffer = await sharp(join(FOTO_DIR, file))
    .resize(20, 20, { fit: "inside" })
    .toFormat("webp", { quality: 40 })
    .toBuffer();
  const key = `/foto/${file}`;
  entries[key] = `data:image/webp;base64,${buffer.toString("base64")}`;
  console.log(`blur ${key} (${buffer.length} bytes)`);
}

const body = `// AUTO-GENERATED by scripts/gen-blur.mjs — do not edit by hand.
// Base64 blur placeholders keyed by public path, used by next/image.
export const blurData: Record<string, string> = ${JSON.stringify(entries, null, 2)};

export function blurFor(src: string): string | undefined {
  return blurData[src];
}
`;

await writeFile(OUT_FILE, body);
console.log(`\nWrote ${Object.keys(entries).length} placeholders to ${OUT_FILE}`);
